Fix XStream error that breaks neo4j (3.5) licensing/licensing-requirements-base.xml
com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:71)

eclipse/openj9#2555